### ISSUE TITLE
installation trouble

### ISSUE THREAD

**Issue by AndKe** [rasmushauschild/easyeda2kicad_plugin#1]
I copied the plugin into this direectory:

```
andre@andre-wks:~/.local/share/kicad/8.0/scripting/plugins$ ls
 easyeda2kicad  'LCSC Importer.py'   README.md
```

(this directory is that same that opens when I click  "tools->external plugins.->open plugin directory"  in PCB editor)

clicking "tools->external plugins.->refresh plugins"  does not list the plugin
and it is not listed in  ""tools->external plugins."

So I am stuck on  step four.   "Launch KiCad  - Start KiCad and open the PCB editor. Run the plugin once to initialize."

please advise.

**Comment by rasmushauschild** [comment]
Hi André, thanks for getting in touch!

I’ve only tested this plugin on Mac so far, and it seems like you’re running on Linux, so it might be a platform-specific issue.

I have a Linux machine with KiCad installed, so I’ll try to get it working on that tomorrow.

Stay tuned :)

**Comment by rasmushauschild** [comment]
Hi André,

I believe your issue was caused by a missing dependency. The plugin now tells you if you are missing any packages, and how til install them. It also saves a log file.

I updated the install guide, so it should hopefully work for you now!

Let me know how it goes :)

**Comment by AndKe** [comment]
Thank you, I plan to test it tomorrow (in 10-14 hrs.)

**Comment by AndKe** [comment]
Works great, I see that it is saving by default to another place: /home/your_username/Documents/Kicad/easyeda2kicad/
Is there a reason for not using and the ~/.local/share/kicad/8.0 and  3dmodels/symbols/footprints dirs that are already there?

**Comment by rasmushauschild** [comment]
Great to hear!

The default library location is a result of the easyeda2kicad command line tool, this plugin is based on.
I believe it was done to make the libraries easily accessible to multiple installations of KiCad, or when you update.

I'm sure you can change it if you look into the source code for easyeda2kicad.
